# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI with Extension Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Static analysis
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test ember-template-lint
        working-directory: ./test-fixtures/sample-project
        run: |
          yarn install
          echo "Piping a string to stdin:"
          cat foo/rule-violation.hbs | node_modules/.bin/ember-template-lint --json --filename foo/rule-violation.hbs
          echo "Direct file input:"
          node_modules/.bin/ember-template-lint --json foo/rule-violation.hbs
          echo "Done with test commands"
        shell: sh {0}
      - name: Run integration tests
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: yarn test
